version: '3.1'


services:
  database:
    image: mariadb:10-jessie
    restart: always
    volumes:
      - "~/.filtermanager-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: citadel

#    networks:
#      default:
#        aliases:
#          - database

  redis:
    image: redis:4
#    networks:
#      default:
#        aliases:
#          - redis-host

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/var/www"
#    networks:
#      default:
#        aliases:
#          - web-host
    depends_on:
      - database
      - redis
    ports:
      - "8000:80"
      - "8443:443"
