version: '3.1'

volumes:
  mariadb_data:
    external: true

services:
  database:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./share:/root/share
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: citadel

#    networks:
#      default:
#        aliases:
#          - database

  redis:
    image: redis:4
#    networks:
#      default:
#        aliases:
#          - redis-host

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/var/www"
#    networks:
#      default:
#        aliases:
#          - web-host
    depends_on:
      - database
      - redis
    ports:
      - "8000:80"
      - "8443:443"
